/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* src = "full_adder.v:1.1-8.10" *)
module full_adder(A, B, Cin, sum, carry);
  wire _0_;
  wire _1_;
  (* src = "full_adder.v:2.7-2.8" *)
  input A;
  wire A;
  (* src = "full_adder.v:2.9-2.10" *)
  input B;
  wire B;
  (* src = "full_adder.v:2.11-2.14" *)
  input Cin;
  wire Cin;
  (* src = "full_adder.v:3.13-3.18" *)
  output carry;
  wire carry;
  (* src = "full_adder.v:3.8-3.11" *)
  output sum;
  wire sum;
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _2_ (
    .A1(A),
    .A2(Cin),
    .ZN(_0_)
  );
  gf180mcu_fd_sc_mcu9t5v0__xor3_1 _3_ (
    .A1(A),
    .A2(B),
    .A3(Cin),
    .Z(sum)
  );
  gf180mcu_fd_sc_mcu9t5v0__oai21_1 _4_ (
    .A1(A),
    .A2(Cin),
    .B(B),
    .ZN(_1_)
  );
  gf180mcu_fd_sc_mcu9t5v0__nand2_1 _5_ (
    .A1(_0_),
    .A2(_1_),
    .ZN(carry)
  );
endmodule

(* dynports =  1  *)
(* top =  1  *)
(* src = "rca.v:1.1-19.10" *)
module rca(A, B, Cin, SUM, Cout);
  (* src = "rca.v:3.20-3.21" *)
  input [7:0] A;
  wire [7:0] A;
  (* src = "rca.v:3.22-3.23" *)
  input [7:0] B;
  wire [7:0] B;
  (* src = "rca.v:4.7-4.10" *)
  input Cin;
  wire Cin;
  (* src = "rca.v:6.8-6.12" *)
  output Cout;
  wire Cout;
  (* src = "rca.v:5.21-5.24" *)
  output [7:0] SUM;
  wire [7:0] SUM;
  (* src = "rca.v:8.15-8.20" *)
  wire [8:0] carry;
  (* module_not_derived = 32'd1 *)
  (* src = "rca.v:16.13-16.85" *)
  full_adder \genblk1[0].FA  (
    .A(A[0]),
    .B(B[0]),
    .Cin(Cin),
    .carry(carry[1]),
    .sum(SUM[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca.v:16.13-16.85" *)
  full_adder \genblk1[1].FA  (
    .A(A[1]),
    .B(B[1]),
    .Cin(carry[1]),
    .carry(carry[2]),
    .sum(SUM[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca.v:16.13-16.85" *)
  full_adder \genblk1[2].FA  (
    .A(A[2]),
    .B(B[2]),
    .Cin(carry[2]),
    .carry(carry[3]),
    .sum(SUM[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca.v:16.13-16.85" *)
  full_adder \genblk1[3].FA  (
    .A(A[3]),
    .B(B[3]),
    .Cin(carry[3]),
    .carry(carry[4]),
    .sum(SUM[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca.v:16.13-16.85" *)
  full_adder \genblk1[4].FA  (
    .A(A[4]),
    .B(B[4]),
    .Cin(carry[4]),
    .carry(carry[5]),
    .sum(SUM[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca.v:16.13-16.85" *)
  full_adder \genblk1[5].FA  (
    .A(A[5]),
    .B(B[5]),
    .Cin(carry[5]),
    .carry(carry[6]),
    .sum(SUM[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca.v:16.13-16.85" *)
  full_adder \genblk1[6].FA  (
    .A(A[6]),
    .B(B[6]),
    .Cin(carry[6]),
    .carry(carry[7]),
    .sum(SUM[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rca.v:16.13-16.85" *)
  full_adder \genblk1[7].FA  (
    .A(A[7]),
    .B(B[7]),
    .Cin(carry[7]),
    .carry(Cout),
    .sum(SUM[7])
  );
  assign { carry[8], carry[0] } = { Cout, Cin };
endmodule
